const fixtures=require('./fixtures.cjs');
const assert=require('node:assert/strict'),F=require('../dist/engine.js');let n=0;
const test=(name,fn)=>{fn();console.log('OK '+name);n++;},clone=s=>F.restore(JSON.stringify(s)),ok=(s,c)=>assert.equal(fixtures.perform(s,c).ok,true,JSON.stringify(c)),hire=(s,slot=0,crew=0)=>ok(s,{type:'employment',action:'hire',slot,crew});
function setup(){const s=fixtures.fresh();s.money=10000;s.rng=1000;for(const [material,quantity]of Object.entries(s.incoming))if(quantity)ok(s,{type:'store',material,quantity});return s;}
test('machine purchase needs no staff; only its own on-duty hire unlocks production',()=>{const s=setup();ok(s,{type:'machine',slot:1,action:'buy'});const raw={...s.raw};assert.ok(F.canCast(s,0));hire(s,1,0);hire(s,0,1);assert.ok(F.canCast(s,0));assert.equal(F.act(s,0,'cast').ok,false);assert.deepEqual(s.raw,raw);hire(s);assert.equal(F.canCast(s,0),'');assert.equal(F.canCast(s,1),'');assert.equal(fixtures.perform(s,{type:'employment',action:'hire',slot:2,crew:0}).ok,false);assert.equal(fixtures.perform(s,{type:'employment',action:'hire',slot:0,crew:3}).ok,false);});
test('hiring is free; partial wages persist on dismissal and reload',()=>{const s=setup();F.tick(s,30);const cash=s.money;hire(s);assert.equal(s.money,cash);F.tick(s,15);assert.equal(s.payroll.operatorAccrued[0],4);ok(s,{type:'employment',action:'dismiss',slot:0,crew:0});const r=clone(s);F.tick(r,F.nextPay(r)-r.clock);assert.equal(r.payroll.history[0].due,1500);assert.equal(r.payroll.history[0].operators[0].name,'Boris');assert.equal(r.payroll.history[0].operators[0].amount,4);assert.equal(r.money,cash-1500);});
test('three hired shifts add 16 + 16 + 24 wages per day, exactly once',()=>{const s=setup();for(let crew=0;crew<3;crew++)hire(s,0,crew);assert.equal(F.shiftWages(2,s),120);F.tick(s,150);const r=clone(s);assert.deepEqual(r.operators,s.operators);assert.deepEqual(r.payroll,s.payroll);F.tick(r,F.nextPay(r)-r.clock);assert.equal(r.payroll.paid,1870);assert.deepEqual(r.payroll.history[0].operators.map(o=>Math.round(o.amount)),[112,112,150]);F.tick(r,F.WEEK);assert.equal(r.payroll.history[0].due,1960);});
test('unloading reserves capacity, survives save and deposits exactly one item on pallet',()=>{const s=setup();hire(s);ok(s,{type:'machine',slot:0,action:'cast'});assert.equal(fixtures.perform(s,{type:'employment',action:'dismiss',slot:0,crew:0}).ok,false);F.tick(s,29.5);assert.equal(s.machines[0].state,'unloading');assert.equal(s.goods.iron_pipe,0);assert.equal(F.reservedOutput(s),1);assert.equal(fixtures.perform(s,{type:'employment',action:'dismiss',slot:0,crew:0}).ok,false);const r=clone(s);F.tick(r,0);assert.ok(Math.abs(r.machines[0].unloadElapsed-1.5)<1e-8);F.tick(r,2.5);assert.equal(r.goods.iron_pipe,1);assert.equal(r.pallets[0].iron_pipe,1);assert.equal(F.used(r,'goods'),1);assert.equal(F.reservedOutput(r),0);F.tick(r,1);assert.equal(r.goods.iron_pipe,1);});
test('shift without replacement safely finishes batch, waits to unload and cannot restart',()=>{const s=setup();s.clock=100;hire(s);ok(s,{type:'machine',slot:0,action:'cast'});F.tick(s,28);assert.equal(F.shift(s),1);assert.equal(s.machines[0].state,'ready');assert.equal(s.goods.iron_pipe,0);assert.equal(F.act(s,0,'collect').ok,false);hire(s,0,1);F.tick(s,4);assert.equal(s.goods.iron_pipe,1);assert.equal(s.pallets[0].iron_pipe,1);ok(s,{type:'employment',action:'dismiss',slot:0,crew:1});assert.ok(F.canCast(s,0));});
test('both pipe types must be cleaned; no direct, market, limit or contract bypass',()=>{for(const id of Object.keys(F.WASH.outputs)){const s=setup();s.goods[id]=2;s.pallets[0][id]=2;const cash=s.money;assert.equal(fixtures.perform(s,{type:'trade',item:'goods:'+id,side:'sell',quantity:1}).ok,false);assert.equal(fixtures.perform(s,{type:'limit',product:id,quantity:1,minPrice:1}).ok,false);assert.equal(F.act(s,0,'sell').ok,false);s.contracts[0].product=id;assert.equal(fixtures.perform(s,{type:'contract',id:s.contracts[0].id,action:'accept'}).ok,false);assert.equal(s.money,cash);ok(s,{type:'washer',action:'configure',product:id});ok(s,{type:'washer',action:'start'});assert.equal(s.goods[id],1);assert.equal(s.pallets[0][id],1);F.tick(s,14);ok(s,{type:'trade',item:'goods:'+F.WASH.outputs[id],side:'sell',quantity:1});assert.equal(s.sold,1);}});
test('every finished/intermediate product refuses purchase; raw trading remains available',()=>{const s=setup();for(const id of Object.keys(F.PRODUCTS)){const before=JSON.stringify(s);assert.equal(fixtures.perform(s,{type:'trade',item:'goods:'+id,side:'buy',quantity:1}).ok,false);assert.equal(JSON.stringify(s),before);}ok(s,{type:'trade',item:'raw:iron',side:'buy',quantity:1});ok(s,{type:'trade',item:'raw:iron',side:'sell',quantity:1});});
test('pallet stock is consumed once by direct, limit and contract sales',()=>{for(const mode of ['trade','limit','contract']){const s=setup();s.goods.clean_ring=3;s.pallets[0].clean_ring=2;s.pallets[1].clean_ring=1;if(mode==='trade')ok(s,{type:mode,item:'goods:clean_ring',side:'sell',quantity:2});if(mode==='limit'){ok(s,{type:mode,product:'clean_ring',quantity:2,minPrice:1});F.tick(s,15);}if(mode==='contract'){const c=s.contracts[0];c.product='clean_ring';c.quantity=2;ok(s,{type:mode,id:c.id,action:'accept'});ok(s,{type:mode,id:c.id,action:'fulfill'});}assert.equal(s.goods.clean_ring,1);assert.equal(s.pallets.reduce((n,p)=>n+p.clean_ring,0),1);}});
test('v9 migration preserves inventory, cash and work; cancels raw limits and extends converted active contracts only once',()=>{const s=setup();s.version=9;s.goods.iron_pipe=4;s.limits=[{id:1,product:'iron_pipe',quantity:3,minPrice:999,created:s.clock}];const c=s.contracts[0];c.product='iron_pipe';c.status='active';c.deadline=s.clock+1;const payout=c.payout;hire(s);F.act(s,0,'cast');F.tick(s,.5);const r=clone(s);assert.equal(r.money,s.money);assert.deepEqual(r.goods,s.goods);assert.equal(r.machines[0].state,'working');assert.equal(F.operatorCount(r,0),0);assert.equal(r.limits.length,0);assert.equal(r.contracts[0].product,'clean_iron_pipe');assert.equal(r.contracts[0].payout,payout);assert.equal(r.contracts[0].deadline,r.clock+135);F.tick(r,10);assert.equal(clone(r).contracts[0].deadline,s.clock+135);});
test('new offers never request unwashed pipes',()=>{const s=setup();s.unlocked=Object.keys(F.PRODUCTS).filter(id=>!F.PRODUCTS[id].finished);for(let i=0;i<8;i++){F.tick(s,180);assert.ok(s.contracts.every(c=>F.saleable(c.product)));}});
console.log(n+' staffing and sales checks passed.');
