const assert=require('node:assert/strict'),F=require('../dist/engine.js');let n=0;
const test=(name,fn)=>{fn();n++;console.log('OK '+name);},near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),copy=s=>F.restore(JSON.stringify(s)),key=(role,crew=0,slot=-1)=>F.positionKey(role,crew,slot),ok=(s,c)=>{const r=F.perform(s,{type:'personnel',...c});assert.equal(r.ok,true,r.message);return r;};
function setup(){const old=F.fresh();old.raw={iron:36,steel:15,copper:8,tin:3,zinc:16};old.incoming=Object.fromEntries(Object.keys(F.MATERIALS).map(id=>[id,0]));old.version=11;delete old.hr;const s=F.restore(JSON.stringify(old));s.money=100000;s.rng=1000;s.hr.rng=202;for(const e of s.hr.employees)e.absence=1;for(const [material,quantity]of Object.entries(s.incoming))if(quantity)assert.equal(F.perform(s,{type:'store',material,quantity}).ok,true);return s;}
function hire(s,role='operator',crew=0,slot=0){const position=key(role,crew,slot),c=s.hr.candidates[position][0];ok(s,{action:'hire',position,candidateId:c.id});return F.assigned(s,position);}
function absent(s,role,crew=F.shift(s),slot=-1){const p=key(role,crew,slot),e=F.assigned(s,p);s.hr.attendance[p]={cycle:Math.floor((s.clock-45+1e-8)/(role==='foreman'?90:60)),employeeId:e.id,absent:true};return e;}
test('all existing roles have individual records and every vacancy has 2–5 stable, differently paid candidates',()=>{const s=setup();assert.equal(s.hr.employees.length,11);assert.equal(F.positions(s).length,17);for(const [position,list] of Object.entries(s.hr.candidates)){assert.ok(list.length>=2&&list.length<=5);for(const c of list){if(F.hasDefect(position.split(':')[0]))assert.ok(c.defect>=1&&c.defect<=15);else assert.equal(Object.hasOwn(c,'defect'),false);assert.ok(c.absence>=.5&&c.absence<=10);}}assert.deepEqual(copy(s).hr.candidates,s.hr.candidates);});
test('hire requires a listed candidate; negotiated salary and skills persist for the chosen position',()=>{const s=setup(),position=key('operator',0,0),c=s.hr.candidates[position].at(-1),money=s.money;assert.equal(F.perform(s,{type:'employment',action:'hire',slot:0,crew:0}).ok,false);ok(s,{action:'hire',position,candidateId:c.id});const e=F.assigned(s,position);assert.equal(e.salary,c.salary);assert.equal(e.defect,c.defect);assert.equal(e.absence,c.absence);assert.equal(e.hiredAt,s.clock);assert.equal(s.money,money);assert.equal(F.duty(s,'operator',0).id,e.id);assert.deepEqual(copy(s).hr.employees,s.hr.employees);assert.equal(F.perform(s,{type:'personnel',action:'hire',position,candidateId:c.id}).ok,false);});
test('each profession can be dismissed and recruited, including both 12-hour foremen',()=>{for(const role of ['ladle','furnace','warehouse','foreman']){const s=setup(),old=F.assigned(s,key(role));ok(s,{action:'dismiss',employeeId:old.id});assert.equal(F.duty(s,role),null);assert.ok(s.hr.candidates[key(role)].length>=2);const e=hire(s,role,0,-1);assert.equal(F.duty(s,role).id,e.id);}const s=setup();assert.equal(F.regularShiftPay(F.assigned(s,key('foreman',1))),40);});
test('absence is rolled once at shift start and survives reload, actions and small ticks',()=>{const s=setup();s.clock=104.99;F.assigned(s,key('ladle',1)).absence=10;s.hr.rng=2000;F.tick(s,.01);const e=F.assigned(s,key('ladle',1)),rng=s.hr.rng;assert.equal(F.duty(s,'ladle'),null);assert.equal(s.hr.attendance[e.position].absent,true);const r=copy(s);assert.equal(r.hr.rng,rng);F.tick(r,.2);assert.equal(r.hr.rng,rng);assert.equal(F.duty(r,'ladle'),null);assert.ok(F.overtimeChoices(r,e.position).length);});
test('absent workers earn nothing; manually called replacement earns 50% overtime only for actual time',()=>{const s=setup();s.clock=105;F.tick(s,.01);const missing=absent(s,'ladle',1),sub=F.assigned(s,key('ladle',0)),before=F.employee(s,missing.id);const initial=s.hr.lines[missing.id]?.normal||0;ok(s,{action:'overtime',position:missing.position,employeeId:sub.id});assert.equal(F.duty(s,'ladle').id,sub.id);F.tick(s,10);near(s.hr.lines[sub.id].overtime,sub.salary*10/60*1.5);near(s.hr.lines[before.id]?.normal||0,initial);assert.equal(F.perform(s,{type:'personnel',action:'overtime',position:missing.position,employeeId:sub.id}).ok,false);});
test('night overtime applies both the night premium and the overtime multiplier',()=>{const s=setup();s.clock=165;F.tick(s,.01);const missing=absent(s,'warehouse',2),sub=F.assigned(s,key('warehouse',0));ok(s,{action:'overtime',position:missing.position,employeeId:sub.id});F.tick(s,20);near(s.hr.lines[sub.id].overtime,sub.salary*20/60*1.5*1.5);});
test('substitution rejects wrong professions, on-duty staff and employees already covering another machine',()=>{const s=setup();F.act(s,1,'buy');const sub=hire(s,'operator',1,0);const missing=key('operator',0,0),other=key('operator',0,1);assert.equal(F.perform(s,{type:'personnel',action:'overtime',position:missing,employeeId:F.duty(s,'warehouse').id}).ok,false);ok(s,{action:'overtime',position:missing,employeeId:sub.id});assert.equal(F.perform(s,{type:'personnel',action:'overtime',position:other,employeeId:sub.id}).ok,false);assert.equal(F.perform(s,{type:'personnel',action:'overtime',position:missing,employeeId:F.duty(s,'ladle').id}).ok,false);});
test('overtime persists on reload and expires at the target shift boundary',()=>{const s=setup(),sub=hire(s,'operator',1,0);ok(s,{action:'overtime',position:key('operator',0,0),employeeId:sub.id});F.tick(s,15);const r=copy(s);assert.deepEqual(r.hr.covers,s.hr.covers);F.tick(r,45);assert.equal(r.hr.covers.length,0);const earned=r.hr.lines[sub.id].overtime;F.tick(r,1);near(r.hr.lines[sub.id].overtime,earned);});
test('severance thresholds are exact at 28 / 56 / 84 days and cap at four weeks',()=>{const s=setup(),e=F.assigned(s,key('warehouse',2));for(const [months,multiple]of [[.99,0],[1,1],[1.99,1],[2,2],[2.99,2],[3,4],[7,4]]){s.clock=e.hiredAt+months*F.MONTH;assert.equal(F.severance(s,e),Math.round(F.weeklyPay(e)*multiple));}const foreman=F.assigned(s,key('foreman',1));s.clock=foreman.hiredAt+3*F.MONTH;assert.equal(F.severance(s,foreman),1120);});
test('dismissal adds severance once to weekly payroll and preserves accrued wages after replacement',()=>{const s=setup(),e=F.duty(s,'warehouse');F.tick(s,10);const wage=s.hr.lines[e.id].normal;s.clock=e.hiredAt+2*F.MONTH;const extra=F.severance(s,e),cash=s.money,before=s.payroll.accrued;ok(s,{action:'dismiss',employeeId:e.id});assert.equal(s.money,cash);near(s.payroll.accrued,before+extra);near(s.hr.lines[e.id].normal,wage);assert.equal(s.hr.lines[e.id].severance,extra);assert.equal(F.perform(s,{type:'personnel',action:'dismiss',employeeId:e.id}).ok,false);hire(s,'warehouse',0,-1);const r=copy(s);assert.equal(r.hr.lines[e.id].severance,extra);F.tick(r,F.nextPay(r)-r.clock);const line=r.payroll.history[0].employees.find(l=>l.employeeId===e.id);assert.equal(line.severance,extra);near(line.normal,wage);assert.equal(r.hr.lines[e.id],undefined);});
test('absence and vacancies block only dependent jobs; replacements restore operation',()=>{for(const role of ['ladle','furnace','foreman','operator']){const s=setup();hire(s);absent(s,role,0,role==='operator'?0:-1);assert.ok(F.canCast(s,0));}const s=setup();absent(s,'warehouse');assert.equal(F.perform(s,{type:'store',material:'iron',quantity:1}).ok,false);s.goods.iron_pipe=1;assert.ok(F.canWash(s));s.goods.ring=1;assert.equal(F.perform(s,{type:'trade',item:'goods:ring',side:'sell',quantity:1}).ok,false);});
test('quality adds machine and operator risk and ignores other roles',()=>{const s=setup();hire(s);for(const e of s.hr.employees)e.defect=1;const m=s.machines[0];near(F.totalFailureRisk(s,m,0),.31);for(const role of ['ladle','furnace','operator'])F.duty(s,role,role==='operator'?0:-1).defect=15;near(F.totalFailureRisk(s,m,0),.45);F.duty(s,'warehouse').defect=15;near(F.totalFailureRisk(s,m,0),.45);assert.equal(F.totalFailureRisk(s,{...m,product:'ring'},0),0);});
test('busy employees cannot be dismissed and in-flight work survives shift handover and reload',()=>{const s=setup(),e=hire(s);s.clock=100;assert.equal(F.act(s,0,'cast').ok,true);assert.equal(F.perform(s,{type:'personnel',action:'dismiss',employeeId:e.id}).ok,false);F.tick(s,4);const pan=F.employee(s,s.delivery.employeeId);assert.equal(F.perform(s,{type:'personnel',action:'dismiss',employeeId:pan.id}).ok,false);const r=copy(s);F.tick(r,28);assert.equal(r.machines[0].state,'ready');assert.equal(r.goods.iron_pipe,0);});
test('v11 saves retain workers, money and wages without inventing past tenure or back-charging',()=>{const s=setup();s.version=11;s.operators[0][0]=true;s.clock=8000;s.payroll.accrued=123;s.payroll.debt=20;delete s.hr;const r=copy(s);assert.equal(r.money,s.money);assert.equal(r.payroll.accrued,123);assert.equal(r.payroll.debt,20);assert.equal(r.hr.lines.legacy.normal,123);assert.equal(F.assigned(r,key('operator',0,0)).name,'Boris');assert.ok(r.hr.employees.every(e=>e.hiredAt===8000));assert.deepEqual(copy(r).hr,r.hr);});
test('weekly payments use actual negotiated salaries and retain employee names in history after reload',()=>{const s=setup(),e=hire(s);e.salary=37;e.absence=1;s.hr.rng=202;F.tick(s,60);near(s.hr.lines[e.id].normal,37);const r=copy(s);assert.equal(F.employee(r,e.id).salary,37);F.tick(r,F.nextPay(r)-r.clock);const h=r.payroll.history[0],line=h.employees.find(l=>l.employeeId===e.id);near(line.normal,37*7);assert.equal(copy(r).payroll.history[0].employees.find(l=>l.employeeId===e.id).name,e.name);});
test('large and small steps produce the same absences, payroll and overtime expiration',()=>{const s=setup();hire(s);const a=copy(s),b=copy(s);F.tick(a,1260);for(let i=0;i<12600;i++)F.tick(b,.1);assert.equal(a.hr.rng,b.hr.rng);assert.equal(a.payroll.paid,b.payroll.paid);assert.equal(a.money,b.money);assert.deepEqual(a.hr.attendance,b.hr.attendance);near(a.payroll.accrued,b.payroll.accrued);});
test('fresh games employ only the two foremen; every other position requires hiring',()=>{const s=F.fresh();assert.deepEqual(s.hr.employees.map(e=>e.name),['Mišo (Majster)','Miro (Majster)']);assert.equal(s.money,1000);assert.equal(Object.keys(s.hr.candidates).length,15);assert.equal(F.duty(s,'warehouse'),null);assert.equal(F.perform(s,{type:'store',material:'iron',quantity:1}).ok,false);assert.deepEqual(copy(s).hr.employees,s.hr.employees);for(const role of ['ladle','furnace','warehouse'])hire(s,role,0,-1);hire(s);assert.equal(F.act(s,0,'cast').ok,true);});
test('salary strictly increases for either improved statistic and is independent of candidate order',()=>{for(const role of Object.keys(F.WAGES))for(let d=1;d<=15;d++)for(let a=.5;a<=10;a+=.5){const v=F.candidateSalary(role,d,a);if(d>1){if(F.hasDefect(role))assert.ok(F.candidateSalary(role,d-1,a)>v);else assert.equal(F.candidateSalary(role,d-1,a),v);}if(a>.5)assert.ok(F.candidateSalary(role,d,a-.5)>v);assert.ok(v>=F.WAGES[role]*.65-.051&&v<=F.WAGES[role]*1.55+.051);}const s=F.fresh();for(const p of F.positions(s))for(const c of s.hr.candidates[p.key]||[])assert.equal(c.salary,F.candidateSalary(p.role,c.defect,c.absence));const e=s.hr.employees[0];e.salary=25.3;const list=Object.values(s.hr.candidates)[0];list[0].salary=199;const r=copy(s);assert.equal(r.hr.employees[0].salary,25.3);assert.notEqual(Object.values(r.hr.candidates)[0][0].salary,199);});
console.log(n+' personnel checks passed.');
