const fixtures=require('./fixtures.cjs');
const assert=require('node:assert/strict'),F=require('../dist/engine.js');let passed=0;
function test(name,fn){fn();console.log('OK '+name);passed++;}
function setup(seed=2000){const s=fixtures.fresh();s.rng=seed;s.money=100000;for(const [material,quantity]of Object.entries(s.incoming))fixtures.perform(s,{type:'store',material,quantity});for(let crew=0;crew<3;crew++)fixtures.perform(s,{type:"employment",action:"hire",slot:0,crew});return s;}
const clone=s=>F.restore(JSON.stringify(s));
test('all new contracts and recipe-unlock offers retain exactly 75% of previous cash reward',()=>{const s=setup();for(const c of s.contracts)assert.equal(c.payout,Math.round(Math.round(F.PRODUCTS[c.product].base*1.3)*c.quantity*.75));fixtures.perform(s,{type:'unlock',product:'steel_pipe'});const c=s.contracts.at(-1);assert.equal(c.payout,Math.round(Math.round(F.PRODUCTS.clean_steel_pipe.base*1.3)*2*.75));});
test('old stocks, receiving dock and upgraded coke bin migrate to zinc once',()=>{const s=setup();s.version=6;s.raw.coke=s.raw.zinc;delete s.raw.zinc;s.incoming.coke=9;delete s.incoming.zinc;s.bins.coke=3;delete s.bins.zinc;for(const c of s.contracts)c.payout=400;s.contracts[0].status='active';s.contracts[0].deadline=s.clock+100;s.contracts[1].status='done';const r=clone(s);assert.equal(r.raw.zinc,16);assert.equal(r.incoming.zinc,9);assert.equal(r.bins.zinc,3);assert.equal(F.binCapacity(r,'zinc'),160);assert.equal('coke' in r.raw,false);assert.equal(r.contracts[0].payout,300);assert.equal(r.contracts[1].payout,400);assert.equal(r.contracts[2].payout,300);assert.deepEqual(clone(r).contracts,r.contracts);assert.equal(r.money,s.money);assert.equal(F.quote(r,'raw:coke'),null);assert.ok(F.quote(r,'raw:zinc').ask);});
test('rejection consumes ingredients once but creates no goods, sales or milestones',()=>{for(const product of ['iron_pipe','steel_pipe'])for(const level of [1,2,3]){const s=setup(),m=s.machines[0];s.unlocked.push(product);m.product=product;m.level=level;const raw={...s.raw};assert.equal(F.act(s,0,'cast').ok,true);assert.equal(m.reject,true);F.tick(s,F.FLOW.pourEnd);assert.equal(m.state,'failed');assert.equal(s.scrapped,1);assert.equal(s.made,0);assert.equal(s.sold,0);assert.equal(F.used(s,'goods'),0);assert.equal(F.reservedOutput(s),0);assert.equal(F.act(s,0,'sell').ok,false);assert.equal(F.act(s,0,'collect').ok,false);assert.equal(F.act(s,0,'cast').ok,false);for(const [id,n]of Object.entries(F.PRODUCTS[product].recipe))assert.equal(s.raw[id],raw[id]-n);F.tick(s,3.99);assert.equal(m.state,'failed');F.tick(s,.01);assert.equal(m.state,'idle');assert.equal(s.scrapped,1);}});
test('success creates exactly one finished pipe; other products do not roll pipe defects',()=>{const s=setup(1000);F.act(s,0,'cast');assert.equal(s.machines[0].reject,false);F.tick(s,28);assert.equal(s.machines[0].state,'unloading');assert.equal(s.made,1);assert.equal(s.scrapped,0);for(const product of ['ring','bronze_bushing']){const t=setup();t.unlocked.push(product);t.machines[0].product=product;const seed=t.rng;F.act(t,0,'cast');assert.equal(F.failureRisk(t.machines[0]),0);assert.equal(t.rng,seed);F.tick(t,F.duration(1,product));assert.equal(t.made,1);assert.equal(t.scrapped,0);}});
test('exact risk levels and deterministic long-run reject rates',()=>{for(const level of [1,2,3]){const s=setup(912345),m=s.machines[0];m.level=level;s.raw.iron=100000;s.raw.zinc=20000;let rejects=0;const expected=[.3,.2,.1][level-1];assert.equal(F.failureRisk(m),expected);for(let i=0;i<10000;i++){assert.equal(F.act(s,0,'cast').ok,true);rejects+=m.reject?1:0;m.state='idle';s.queue=[];}assert.ok(Math.abs(rejects/10000-(expected+.01))<.015,'Observed rate '+rejects/10000);}});
test('reload cannot reroll a queued batch and preserves an in-progress burst',()=>{const s=setup();F.act(s,0,'cast');F.tick(s,6);const r=clone(s);assert.equal(r.machines[0].reject,true);assert.equal(r.rng,s.rng);F.tick(r,5.5);assert.equal(r.machines[0].state,'failed');const again=clone(r),age=again.machines[0].failedElapsed;F.tick(again,0);assert.equal(again.machines[0].failedElapsed,age);assert.equal(again.scrapped,1);F.tick(again,4-age);assert.equal(again.machines[0].state,'idle');assert.equal(again.scrapped,1);assert.equal(F.used(again,'goods'),0);});
test('rejects release the shared ladle and automatic production resumes safely',()=>{const s=setup();F.act(s,1,'buy');for(let crew=0;crew<3;crew++)fixtures.perform(s,{type:'employment',action:'hire',slot:1,crew});s.machines[0].auto=true;F.act(s,0,'cast');F.act(s,1,'cast');F.tick(s,14.2);assert.equal(s.machines[0].state,'working');assert.equal(s.delivery.slot,1);assert.equal(s.queue[0],0);assert.equal(s.scrapped,1);assert.equal(s.raw.iron,18);assert.equal(s.raw.zinc,13);});
test('large and frame-sized steps agree with rejects and serial production',()=>{const s=setup();s.raw.iron=300;s.raw.zinc=100;s.machines[0].auto=true;F.act(s,1,'buy');for(let crew=0;crew<3;crew++)fixtures.perform(s,{type:'employment',action:'hire',slot:1,crew});s.machines[1].auto=true;const a=clone(s),b=clone(s);F.tick(a,180);for(let i=0;i<10800;i++)F.tick(b,1/60);assert.equal(a.scrapped,b.scrapped);assert.ok(a.scrapped>0);assert.equal(a.made,b.made);assert.equal(a.rng,b.rng);assert.deepEqual(a.raw,b.raw);assert.deepEqual(a.goods,b.goods);assert.equal(a.money,b.money);});
console.log(passed+' rejection and migration checks passed.');
