const fixtures=require('./fixtures.cjs');
const assert=require('node:assert/strict'),F=require('../dist/engine.js');
let passed=0;function test(name,fn){fn();console.log('OK '+name);passed++;}const clone=s=>JSON.parse(JSON.stringify(s)),doIt=(s,c)=>assert.equal(fixtures.perform(s,c).ok,true,JSON.stringify(c));
function hire(s,slot=0){for(let crew=0;crew<3;crew++)doIt(s,{type:"employment",action:"hire",slot,crew});return s;}
function staffed(){return hire(stocked());}
function stocked(){const s=fixtures.fresh();s.rng=1000;for(const [material,quantity]of Object.entries(s.incoming))if(quantity)fixtures.perform(s,{type:'store',material,quantity});return s;}

test('180 seconds per day; exact 06/14/22 shifts',()=>{const s=stocked();assert.equal(F.clockText(s),'06:00');F.tick(s,60);assert.equal(F.clockText(s),'14:00');assert.equal(F.shift(s),1);F.tick(s,60);assert.equal(F.clockText(s),'22:00');assert.equal(F.shift(s),2);F.tick(s,60);assert.equal(F.day(s),2);assert.equal(F.clockText(s),'06:00');assert.equal(s.shiftChanges,3);});
test('material -> work in progress -> inventory -> sale conservation',()=>{const s=staffed(),money=s.money;doIt(s,{type:'machine',slot:0,action:'cast'});assert.equal(s.raw.iron,30);assert.equal(s.raw.zinc,15);assert.equal(F.reservedOutput(s),1);F.tick(s,28);assert.equal(s.machines[0].state,'unloading');assert.equal(s.made,1);assert.equal(F.temperature(s.machines[0]),180);F.tick(s,4);assert.equal(s.goods.iron_pipe,1);doIt(s,{type:'washer',action:'start'});F.tick(s,14);const bid=F.quote(s,'goods:clean_iron_pipe').bid;doIt(s,{type:'trade',item:'goods:clean_iron_pipe',side:'sell',quantity:1});assert.equal(s.goods.clean_iron_pipe,0);assert.equal(s.money,money+bid-6);assert.equal(s.sold,1);assert.equal(fixtures.perform(s,{type:'trade',item:'goods:iron_pipe',side:'sell',quantity:1}).ok,false);});
test('all four products complete with their own recipes and cooling',()=>{for(const [id,p] of Object.entries(F.PRODUCTS).filter(([,p])=>!p.finished)){const s=staffed();s.unlocked.push(id);doIt(s,{type:'machine',slot:0,action:'configure',product:id});const before=clone(s.raw);doIt(s,{type:'machine',slot:0,action:'cast'});for(const [raw,n]of Object.entries(p.recipe))assert.equal(s.raw[raw],before[raw]-n);F.tick(s,13);assert.equal(F.stage(s.machines[0]),'cooling');const hot=F.temperature(s.machines[0]);F.tick(s,3);assert.ok(F.temperature(s.machines[0])<hot);F.tick(s,p.seconds-16);F.tick(s,4);assert.equal(s.goods[id],1);}});
test('single ladle queue and shift handover preserve current operator',()=>{const s=staffed();s.money=2000;doIt(s,{type:'machine',slot:1,action:'buy'});hire(s,1);s.clock=100;doIt(s,{type:'machine',slot:0,action:'cast'});doIt(s,{type:'machine',slot:1,action:'cast'});F.tick(s,6);assert.equal(F.shift(s),1);assert.equal(s.delivery.crew,0);assert.equal(F.stage(s.machines[1]),'waiting');F.tick(s,8);assert.equal(s.delivery.slot,1);assert.equal(s.delivery.crew,1);F.tick(s,40);assert.ok(s.machines.slice(0,2).every(m=>m.state==='idle'));});
test('series stops on missing ingredients and resumes after purchase',()=>{const s=staffed();s.raw.iron=6;s.raw.zinc=1;doIt(s,{type:'machine',slot:0,action:'auto',enabled:true});F.tick(s,60);assert.equal(s.goods.iron_pipe,1);assert.equal(s.machines[0].state,'idle');doIt(s,{type:'trade',item:'raw:iron',side:'buy',quantity:6});doIt(s,{type:'trade',item:'raw:zinc',side:'buy',quantity:1});doIt(s,{type:'store',material:'iron',quantity:6});doIt(s,{type:'store',material:'zinc',quantity:1});F.tick(s,32);assert.equal(s.goods.iron_pipe,2);assert.equal(s.raw.iron,0);});
test('capacity reserves output; full warehouse halts and resumes series',()=>{const s=staffed();s.unlocked.push("ring");s.machines[0].product="ring";s.goods.ring=23;doIt(s,{type:'machine',slot:0,action:'auto',enabled:true});F.tick(s,1);assert.equal(fixtures.perform(s,{type:'trade',item:'goods:ring',side:'buy',quantity:1}).ok,false);F.tick(s,40);assert.equal(s.goods.ring,24);assert.equal(s.machines[0].state,'idle');doIt(s,{type:'washer',action:'configure',product:'ring'});doIt(s,{type:'washer',action:'start'});F.tick(s,14);doIt(s,{type:'trade',item:'goods:clean_ring',side:'sell',quantity:1});F.tick(s,28);assert.equal(s.goods.ring,24);assert.equal(s.machines[0].state,'idle');});
test('limit reservations cannot be sold twice; execute only once',()=>{const s=stocked();s.goods.clean_iron_pipe=4;doIt(s,{type:'limit',product:'clean_iron_pipe',quantity:3,minPrice:1});assert.equal(F.available(s,'clean_iron_pipe'),1);assert.equal(fixtures.perform(s,{type:'trade',item:'goods:clean_iron_pipe',side:'sell',quantity:2}).ok,false);F.tick(s,15);assert.equal(s.limits.length,0);assert.equal(s.goods.clean_iron_pipe,1);assert.equal(s.sold,3);F.tick(s,30);assert.equal(s.sold,3);});
test('cancel releases stock; contracts use unreserved goods and pay once',()=>{const s=stocked(),c=s.contracts[0];s.goods[c.product]=c.quantity;doIt(s,{type:'contract',id:c.id,action:'accept'});doIt(s,{type:'limit',product:c.product,quantity:1,minPrice:9999});assert.equal(fixtures.perform(s,{type:'contract',id:c.id,action:'fulfill'}).ok,false);doIt(s,{type:'cancelLimit',id:s.limits[0].id});const money=s.money;doIt(s,{type:'contract',id:c.id,action:'fulfill'});assert.equal(s.money,money+c.payout);assert.equal(s.goods[c.product],0);assert.equal(s.reputation,2);assert.equal(fixtures.perform(s,{type:'contract',id:c.id,action:'fulfill'}).ok,false);});
test('deadline expiration; offers refresh at midnight',()=>{const s=stocked();s.reputation=2;const c=s.contracts[0];doIt(s,{type:'contract',id:c.id,action:'accept'});F.tick(s,135);assert.equal(c.status,'expired');assert.equal(s.reputation,1);assert.equal(F.day(s),2);assert.ok(s.contracts.some(x=>x.id.startsWith('D2-')));});
test('valid purchases preserve cash/capacity; invalid commands do nothing',()=>{const s=stocked(),before=clone(s);for(const c of [{type:'trade',item:'raw:iron',side:'buy',quantity:-1},{type:'trade',item:'raw:iron',side:'buy',quantity:1000},{type:'trade',item:'unknown',side:'buy',quantity:1},{type:'machine',slot:9,action:'buy'}])assert.equal(fixtures.perform(s,c).ok,false);assert.deepEqual(s,before);doIt(s,{type:'trade',item:'raw:iron',side:'buy',quantity:10});assert.equal(s.raw.iron,36);assert.equal(s.incoming.iron,10);assert.ok(s.money<before.money);});
test('large and frame-sized steps yield the same multi-machine production',()=>{const s=staffed();s.money=10000;s.storage.raw=5;s.storage.goods=5;s.raw.iron=200;s.raw.zinc=70;s.logistics=2;for(let i=1;i<6;i++){F.act(s,i,'buy');hire(s,i);}for(let i=0;i<6;i++)F.act(s,i,'auto',{enabled:true});const a=clone(s),b=clone(s);F.tick(a,180);for(let i=0;i<10800;i++)F.tick(b,1/60);assert.ok(Math.abs(a.clock-b.clock)<1e-5);assert.equal(a.made,b.made);assert.deepEqual(a.goods,b.goods);assert.deepEqual(a.raw,b.raw);assert.equal(a.money,b.money);assert.equal(a.shiftChanges,b.shiftChanges);});
test('saved active work, orders and inventory round-trip; legacy progress migrates',()=>{const s=staffed();s.goods.clean_ring=2;doIt(s,{type:'limit',product:'clean_ring',quantity:1,minPrice:999});F.act(s,0,'cast');F.tick(s,5);const r=F.restore(JSON.stringify(s));assert.deepEqual(r.raw,s.raw);assert.deepEqual(r.goods,s.goods);assert.deepEqual(r.delivery,s.delivery);assert.deepEqual(r.limits,s.limits);F.tick(r,30);assert.equal(r.machines[0].state,'idle');const old={version:2,money:3210,sold:35,selected:0,machines:[{level:3,state:'idle',elapsed:0,served:false},null,null,null,null,null]};const m=F.restore(JSON.stringify(old));assert.equal(m.money,3210);assert.equal(m.sold,35);assert.equal(m.machines[0].level,3);assert.equal(m.raw.iron,36);assert.ok(m.milestones.includes('sales'));});
test('quote boundary executes at the same price for small and large time steps',()=>{const s=stocked();s.goods.clean_iron_pipe=1;doIt(s,{type:'limit',product:'clean_iron_pipe',quantity:1,minPrice:1});const a=clone(s),b=clone(s);F.tick(a,15);for(let i=0;i<900;i++)F.tick(b,1/60);assert.equal(a.money,b.money);assert.equal(a.sold,b.sold);});
test('unknown inherited catalog keys are rejected without corrupting funds',()=>{const s=stocked(),before=clone(s);for(const item of ['raw:constructor','goods:__proto__'])assert.equal(fixtures.perform(s,{type:'trade',item,side:'buy',quantity:1}).ok,false);assert.deepEqual(s,before);});
test('deliveries are unavailable until stored; individual bin limits and upgrades',()=>{const s=hire(fixtures.fresh());assert.equal(s.raw.iron,0);assert.equal(s.incoming.iron,36);assert.ok(F.canCast(s,0));doIt(s,{type:'store',material:'iron',quantity:36});doIt(s,{type:'store',material:'zinc',quantity:16});assert.equal(F.canCast(s,0),'');doIt(s,{type:'trade',item:'raw:iron',side:'buy',quantity:30});assert.equal(s.raw.iron,36);assert.equal(fixtures.perform(s,{type:'store',material:'iron',quantity:30}).ok,false);const copper=F.binCapacity(s,'copper');doIt(s,{type:'expandBin',material:'iron'});assert.equal(F.binCapacity(s,'iron'),120);assert.equal(F.binCapacity(s,'copper'),copper);doIt(s,{type:'store',material:'iron',quantity:30});assert.equal(s.raw.iron,66);assert.equal(s.incoming.iron,0);});
test('receiving capacity and raw sale preserve stock across both locations',()=>{const s=stocked();s.money=10000;doIt(s,{type:'trade',item:'raw:iron',side:'buy',quantity:160});assert.equal(fixtures.perform(s,{type:'trade',item:'raw:copper',side:'buy',quantity:1}).ok,false);doIt(s,{type:'trade',item:'raw:iron',side:'sell',quantity:170});assert.equal(s.incoming.iron,0);assert.equal(s.raw.iron,26);});
test('base wages accrue across all shifts and pay only at the weekly boundary',()=>{const s=stocked();s.money=10000;F.tick(s,180);assert.equal(s.money,10000);assert.equal(s.payroll.accrued,224);assert.equal(s.payroll.history.length,0);F.tick(s,F.nextPay(s)-s.clock);assert.equal(s.money,8504);assert.equal(s.payroll.paid,1496);assert.equal(s.payroll.history.length,1);assert.equal(s.payroll.history[0].weekly,true);F.tick(s,F.WEEK);assert.equal(s.payroll.history[0].due,1568);assert.equal(s.payroll.paid,3064);});
test('weekly debt stops new work but preserves finished goods and resumes after payment',()=>{const s=staffed();s.money=5;s.machines[0].product='ring';F.act(s,0,'cast');F.tick(s,F.nextPay(s)-s.clock);assert.equal(s.machines[0].state,'idle');assert.equal(s.goods.ring,1);assert.equal(s.payroll.debt,1865);assert.equal(fixtures.perform(s,{type:'trade',item:'goods:ring',side:'sell',quantity:1}).ok,false);s.goods.clean_ring=1;doIt(s,{type:'trade',item:'goods:clean_ring',side:'sell',quantity:1});assert.match(F.canCast(s,0),/mzdy/);const accrued=s.payroll.accrued;F.tick(s,120);assert.equal(s.payroll.accrued,accrued);s.money=2000;doIt(s,{type:'payWages'});assert.equal(s.payroll.debt,0);assert.equal(F.canCast(s,0),'');});
test('warehouse/payroll save restores without duplicating or resetting debts',()=>{const s=fixtures.fresh();s.payroll.accrued=12.5;s.payroll.debt=27;s.payroll.paid=5;s.bins.copper=2;const r=F.restore(JSON.stringify(s));assert.equal(r.version,14);assert.deepEqual(r.incoming,s.incoming);assert.deepEqual(r.bins,s.bins);assert.deepEqual(r.payroll,s.payroll);const old=stocked();old.version=3;old.clock=100;old.storage.raw=2;old.raw.iron=350;const migrated=F.restore(JSON.stringify(old));assert.equal(migrated.raw.iron,350);assert.ok(F.binCapacity(migrated,'iron')>=350);assert.equal(F.used(migrated,'incoming'),0);assert.equal(migrated.payroll.accrued,0);F.tick(migrated,5);assert.equal(migrated.payroll.paid,0);assert.ok(Math.abs(migrated.payroll.accrued-16/3)<1e-8);});
test('renamed crews have one warehouse worker and one foreman; all roles earn +50% at night',()=>{assert.deepEqual(F.CREWS.map(p=>p.name),['Miči','Maslo','Matino']);assert.deepEqual(F.FURNACE_CREWS.map(p=>p.name),['Ivan','Palo','Adino']);assert.equal(new Set(F.WAREHOUSE_CREWS.map(p=>p.name)).size,3);for(let i=0;i<3;i++){const team=F.staff({clock:45+i*60});assert.equal(team.filter(p=>p.role==='warehouse').length,1);assert.equal(team.filter(p=>p.role==='foreman').length,1);assert.equal(team.length,4);}for(const role of Object.keys(F.WAGES)){assert.equal(F.wage(role,0),F.wage(role,1));assert.equal(F.wage(role,2),F.wage(role,0)*1.5);}});
test('weekly accrued wages survive reload and pay exactly once',()=>{const s=stocked();s.money=10000;F.tick(s,150);assert.equal(s.payroll.accrued,176);const r=F.restore(JSON.stringify(s));assert.deepEqual(r.payroll,s.payroll);F.tick(r,F.nextPay(r)-r.clock);assert.equal(r.payroll.history[0].due,1496);const again=F.restore(JSON.stringify(r));F.tick(again,.1);assert.equal(again.payroll.paid,1496);assert.equal(again.payroll.history.length,1);});
test('v4 upgrade preserves earned wages and stock without retroactive charges',()=>{const old=stocked();old.version=4;old.clock=195;old.payroll={accrued:16,paid:64,debt:0,history:[{clock:165,crew:1,due:32,paid:32}]};old.incoming.iron=9;old.bins.iron=2;const r=F.restore(JSON.stringify(old));assert.equal(r.money,old.money);assert.equal(r.payroll.accrued,16);assert.deepEqual(r.raw,old.raw);assert.deepEqual(r.incoming,old.incoming);assert.equal(r.payroll.history[0].team,false);F.tick(r,30);assert.equal(r.payroll.accrued,64);assert.equal(r.payroll.paid,64);old.payroll.debt=27;assert.equal(F.restore(JSON.stringify(old)).payroll.debt,27);});
test('foremen alternate at 06 and 18, independently of the 8-hour crews',()=>{const s=stocked();assert.equal(F.FOREMEN[F.foremanShift(s)].name,'Mišo (Majster)');assert.equal(F.nextForemanChange(s),135);F.tick(s,60);assert.equal(F.shift(s),1);assert.equal(F.foremanShift(s),0);F.tick(s,29.999);assert.equal(F.foremanShift(s),0);F.tick(s,.001);assert.equal(F.clockText(s),'18:00');assert.equal(F.shift(s),1);assert.equal(F.foremanShift(s),1);assert.equal(F.nextForemanChange(s),225);assert.equal(F.staff(s).at(-1).name,'Miro (Majster)');F.tick(s,30);assert.equal(F.shift(s),2);assert.equal(F.foremanShift(s),1);F.tick(s,15);assert.equal(F.clockText(s),'00:00');assert.equal(F.foremanShift(s),1);F.tick(s,45);assert.equal(F.clockText(s),'06:00');assert.equal(F.foremanShift(s),0);assert.equal(F.nextForemanChange(s),315);});
test('only on-duty foremen earn wages; both totals accumulate until weekly payday',()=>{const s=stocked();s.money=10000;F.tick(s,90);assert.equal(s.payroll.history.length,0);assert.deepEqual(s.payroll.foremenAccrued,[30,0]);const r=F.restore(JSON.stringify(s));assert.deepEqual(r.payroll,s.payroll);F.tick(r,90);assert.deepEqual(r.payroll.foremenAccrued,[30,40]);assert.equal(r.money,10000);F.tick(r,F.nextPay(r)-r.clock);assert.deepEqual(r.payroll.history[0].foremen,[210,257.5]);assert.equal(r.payroll.paid,1496);});
test('v5 migration preserves cash, debts, history and wages already earned',()=>{const old=stocked();old.version=5;old.clock=150;old.payroll={accrued:48,paid:64,debt:0,history:[{clock:105,crew:0,due:64,paid:64,team:true}]};const r=F.restore(JSON.stringify(old));assert.equal(r.money,1000);assert.equal(r.payroll.accrued,48);assert.deepEqual(r.payroll.foremenAccrued,[0,0]);F.tick(r,15);assert.equal(r.payroll.accrued,64);assert.equal(r.payroll.paid,64);assert.deepEqual(r.payroll.foremenAccrued,[0,5]);old.payroll.debt=17;const debt=F.restore(JSON.stringify(old));F.tick(debt,15);assert.equal(debt.payroll.accrued,48);assert.equal(debt.payroll.debt,17);});
console.log(passed+' simulation checks passed.');
